[package]
name = "consistent_hash"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "hash"

[dependencies]
jni = "0.19"

[profile.release]
panic = "abort"
opt-level = 3
lto = true
codegen-units = 1